# Generated by Django 3.1 on 2020-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='laku', max_length=20)),
                ('packagesize', models.CharField(default=3, max_length=20)),
                ('unitprice', models.IntegerField(default=3)),
                ('unitsinstock', models.IntegerField(default=3)),
                ('companyname', models.CharField(default='lakufirma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='lakufirma', max_length=50)),
                ('contactname', models.CharField(default='tommi', max_length=50)),
                ('address', models.CharField(default='tie 3', max_length=100)),
                ('phone', models.CharField(default='437483434', max_length=20)),
                ('email', models.CharField(default='simo.silli@silli.com', max_length=50)),
                ('country', models.CharField(default='Finland', max_length=20)),
            ],
        ),
    ]
